Laboratoare/DAW Lab 4-7/Controllers/ArticlesController.cs
using DAW_Lab_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace DAW_Lab_4.Controllers
{
    public class ArticlesController : Controller
    {
        private Models.AppContext db = new Models.AppContext();


        // GET: Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include("Category");
            ViewBag.Articles = articles;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }


        // GET: New
        public ActionResult New()
        {
            Article article = new Article();
            article.Categ = GetAllCategories();
            return View(article);
        }

        // POST: New
        [HttpPost]
        public ActionResult New(Article article)
        {
            article.Categ = GetAllCategories();
            article.Date = DateTime.Now;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Articles.Add(article);
                    db.SaveChanges();
                    TempData["message"] = "Articolul a fost adaugat cu succes!";
                    return RedirectToAction("Index");
                }
                return View(article);
            }
            catch (Exception)
            {
                return View(article);
            }
        }


        // GET: Show
        public ActionResult Show(int id)
        {
            var article = db.Articles.Find(id);
            return View(article);
        }


        // GET: Edit
        public ActionResult Edit(int id)
        {
            var article = db.Articles.Find(id);
            article.Categ = GetAllCategories();
            return View(article);
        }

        // PUT: Edit
        [HttpPut]
        public ActionResult Edit(int id, Article requestArticle)
        {
            requestArticle.Categ = GetAllCategories();
            try
            {
                if (ModelState.IsValid)
                {
                    var article = db.Articles.Find(id);
                    if (TryUpdateModel(article))
                    {
                        article.Title = requestArticle.Title;
                        article.Content = requestArticle.Content;
                        article.CategoryId = requestArticle.CategoryId;
                        db.SaveChanges();
                        TempData["message"] = "Articolul a fost editat!";
                        return RedirectToAction("Index");
                    }
                }
                return View(requestArticle);
            }
            catch (Exception)
            {
                return View(requestArticle);
            }
        }


        // DELETE: Delete
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            TempData["message"] = "Articolul a fost sters cu succes!";
            return RedirectToAction("Index");
        }

        [NonAction]
        private IEnumerable<SelectListItem> GetAllCategories()
        {
            // generam o lista goala
            var selectList = new List<SelectListItem>();

            // extragem toate categoriile din baza de date
            var categories = from cat in db.Categories
                             select cat;

            // iteram prin categorii
            foreach (var category in categories)
            {
                // adaugam in lista elementele necesare pentru dropdown
                selectList.Add(new SelectListItem
                {
                    Value = category.CategoryId.ToString(),
                    Text = category.Name.ToString()
                });
            }
            // returnam lista de categorii
            return selectList;
        }
    }
}

Laboratoare/DAW Lab 4-7/Controllers/CategoriesController.cs
using DAW_Lab_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAW_Lab_4.Controllers
{
    public class CategoriesController : Controller
    {
        private Models.AppContext db = new Models.AppContext();

        // GET: Categories
        public ActionResult Index()
        {
            var categories = db.Categories;
            ViewBag.Categories = categories;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }

        //GET: New
        public ActionResult New()
        {
            Category category = new Category();
            return View(category);
        }

        //POST: New
        [HttpPost]
        public ActionResult New(Category category)
        {
            try
            {
                db.Categories.Add(category);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata cu succes!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(category);
            }
        }

        //GET: Show
        public ActionResult Show(int id)
        {
            var category = db.Categories.Find(id);
            return View(category);
        }

        //GET: Edit
        public ActionResult Edit(int id)
        {
            var category = db.Categories.Find(id);
            return View(category);
        }

        //PUT: Edit
        [HttpPut]
        public ActionResult Edit(int id, Category requestCategory)
        {
            try
            {
                var category = db.Categories.Find(id);
                if (TryUpdateModel(category))
                {
                    category.Name = requestCategory.Name;
                    db.SaveChanges();
                    TempData["message"] = "Categoria a fost editata cu succes!";
                    return RedirectToAction("Index");
                }
                return View(requestCategory);
            }
            catch (Exception)
            {
                return View(requestCategory);
            }
        }

        //DELETE: Delete
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["message"] = "Categoria a fost stearsa cu succes!";
            return RedirectToAction("Index");
        }
    }
}

Laboratoare/DAW Lab 4-7/Views/Shared/ArticleInfo.cshtml
<div class="panel-heading">
    <h3 class="panel-title">@Model.Title</h3>
</div>

<div class="panel-body">
    Continut articol: <strong>@Model.Content</strong>
    <br />

    <i class="glyphicon glyphicon-globe"></i> @Model.Category.Name
    <span class="label label-info pull-right">@Model.Date</span>

</div>

Laboratoare/DAW Lab 4-7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Flash news", "Index", "Articles", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Articole", "Index", "Articles")</li>*@
                    <li>@Html.ActionLink("Categorii", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Articol nou", "New", "Articles")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>