Examen/Subiect1/Models/Subscription.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiganAntonioM41.Models
{
    public class Subscription
    {
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "Descrierea abonamentului este obligatorie!")]
        public string Descriere { get; set; }


        [Required(ErrorMessage = "Numarul abonamentului este obligatoriu!")]
        public int Numar { get; set; }


        [Required(ErrorMessage = "Data emiterii este obligatorie!")]
        [DataType(DataType.Date)]
        public DateTime DataEmitere { get; set; }


        [Required(ErrorMessage = "Clientul este obligatoriu!")]
        public int ClientId { get; set; }


        public virtual Client Client { get; set; }


        public IEnumerable<SelectListItem> Cls { get; set; }
    }
}

Examen/Subiect1/Controllers/SubscriptionsController.cs
using BiganAntonioM41.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiganAntonioM41.Controllers
{
    public class SubscriptionsController : Controller
    {
        private Models.AppContext db = new Models.AppContext();


        // GET: Index
        public ActionResult Index()
        {
            var subscriptions = db.Subscriptions.Include("Client");
            ViewBag.Subscriptions = subscriptions;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }


        // GET: New
        public ActionResult New()
        {
            Subscription subscription = new Subscription();
            subscription.Cls = GetAllCls();
            return View(subscription);
        }

        // POST: New
        [HttpPost]
        public ActionResult New(Subscription subscription)
        {
            subscription.Cls = GetAllCls();
            var numere = db.Subscriptions.Select(s => s.Numar).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    if (subscription.DataEmitere < DateTime.Now.Date)
                    {
                        ViewBag.Message = "Data trebuie sa fie una trecuta!";
                        return View(subscription);
                    }
                    if (numere.Contains(subscription.Numar))
                    {
                        ViewBag.Message = "Numarul trebuie sa fie unic!";
                        return View(subscription);
                    }

                    db.Subscriptions.Add(subscription);
                    db.SaveChanges();
                    TempData["message"] = "Abonamentul a fost adaugat cu succes!";
                    return RedirectToAction("Index");
                }
                return View(subscription);
            }
            catch (Exception)
            {
                return View(subscription);
            }
        }


        // GET: Show
        public ActionResult Show(int id)
        {
            var subscription = db.Subscriptions.Find(id);
            return View(subscription);
        }


        // GET: Edit
        public ActionResult Edit(int id)
        {
            var subscription = db.Subscriptions.Find(id);
            subscription.Cls = GetAllCls();
            return View(subscription);
        }

        // PUT: Edit
        [HttpPut]
        public ActionResult Edit(int id, Subscription requestSubscription)
        {
            requestSubscription.Cls = GetAllCls();
            var numere = db.Subscriptions.Where(s => s.Id != requestSubscription.Id).Select(s => s.Numar).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    var article = db.Subscriptions.Find(id);
                    if (TryUpdateModel(article))
                    {
                        if (requestSubscription.DataEmitere < DateTime.Now.Date)
                        {
                            ViewBag.Message = "Data trebuie sa fie una trecuta!";
                            return View(requestSubscription);
                        }
                        if (numere.Contains(requestSubscription.Numar))
                        {
                            ViewBag.Message = "Numarul trebuie sa fie unic!";
                            return View(requestSubscription);
                        }

                        article.Descriere = requestSubscription.Descriere;
                        article.Numar = requestSubscription.Numar;
                        article.DataEmitere = requestSubscription.DataEmitere;
                        article.ClientId = requestSubscription.ClientId;
                        db.SaveChanges();
                        TempData["message"] = "Abonamentul a fost editat!";
                        return RedirectToAction("Index");
                    }
                }
                return View(requestSubscription);
            }
            catch (Exception)
            {
                return View(requestSubscription);
            }
        }


        // DELETE: Delete
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var subscription = db.Subscriptions.Find(id);
            db.Subscriptions.Remove(subscription);
            db.SaveChanges();
            TempData["message"] = "Abonamentul a fost sters cu succes!";
            return RedirectToAction("Index");
        }

        //GET: Search
        public ActionResult Search(string token, string sort)
        {
            var subscriptions = db.Subscriptions.Include("Client").ToArray();

            List<Subscription> subscriptionsList = new List<Subscription>();

            if (!(token is null))
            {
                foreach (var subscription in subscriptions)
                {
                    if (subscription.Descriere.Contains(token) || subscription.DataEmitere.ToString("dd/MM/yyyy") == token)
                    {
                        subscriptionsList.Add(subscription);
                    }
                }
            }
            

            subscriptions = subscriptionsList.ToArray();


            switch (sort)
            {
                case "dateAsc":
                    subscriptions = subscriptions.OrderBy(s => s.DataEmitere).ToArray();
                    break;
                default:
                    subscriptions = subscriptions.OrderByDescending(s => s.DataEmitere).ToArray();
                    break;
            }

            ViewBag.Subscriptions = subscriptions;
            ViewBag.Search = token;
            return View();
        }

        #region Helpers
        [NonAction]
        private IEnumerable<SelectListItem> GetAllCls()
        {
            var selectList = new List<SelectListItem>();
            var clients = db.Clients;

            foreach (var client in clients)
            {
                selectList.Add(new SelectListItem
                {
                    Value = client.Id.ToString(),
                    Text = client.Nume.ToString()
                });
            }
            
            return selectList;
        }
        #endregion
    }
}

Examen/Subiect1/Views/Subscriptions/Edit.cshtml
@model BiganAntonioM41.Models.Subscription

<h1>Editare articol</h1>

<p class="text-danger">@ViewBag.Message</p>

@using (Html.BeginForm("Edit", "Subscriptions", Model.Id))
{
    @Html.HttpMethodOverride(HttpVerbs.Put)

    @Html.ValidationSummary(false, null, new { @class = "text-danger" })

    @Html.Hidden("Id")

    @Html.Label("Descriere", "Descriere abonament")
    @Html.Editor("Descriere", new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessage("Descriere", null, new { @class = "text-danger" })
    <br />

    @Html.Label("Numar", "Numar abonament")
    @Html.Editor("Numar", new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessage("Numar", null, new { @class = "text-danger" })
    <br />

    @Html.Label("DataEmitere", "Data emitere abonament")
    @Html.TextBox("DataEmitere", Model.DataEmitere.ToString(), new { @class = "form-control datepicker", @placeholder = "Introduceti data" })
    @Html.ValidationMessage("DataEmitere", null, new { @class = "text-danger" })
    <br />

    @Html.Label("ClientId", "Selectati categoria")
    @Html.DropDownList("ClientId", new SelectList(Model.Cls, "Value", "Text"), null, new { @class = "form-control" })
    @Html.ValidationMessage("ClientId", null, new { @class = "text-danger" })
    <br />

    <button class="btn btn-success" type="submit">Editare abonament</button>
}

Examen/Subiect1/Views/Subscriptions/Index.cshtml
@{
    ViewBag.Title = "Subscriptions";
}

<h1>@ViewBag.Title</h1>

<h2>@ViewBag.Message</h2>


@foreach (BiganAntonioM41.Models.Subscription subscription in ViewBag.Subscriptions)
{
    <div class="panel panel-default">
        @Html.Partial("SubscriptionInfo", subscription)

        <div class="panel-footer">
            <a class="btn btn-success btn-sm" href="/Subscriptions/Show/@subscription.Id">Afisare abonament</a>
        </div>
    </div>
}

Examen/Subiect1/Views/Subscriptions/New.cshtml
@model BiganAntonioM41.Models.Subscription

<h1>Adaugare abonament</h1>

<p class="text-danger">@ViewBag.Message</p>

@using (Html.BeginForm("New", "Subscriptions"))
{
    @Html.ValidationSummary(false, null, new { @class = "text-danger" })

    @Html.Label("Descriere", "Descriere abonament")
    @Html.TextBox("Descriere", null, new { @class = "form-control" })
    @Html.ValidationMessage("Descriere", null, new { @class = "text-danger" })
    <br />

    @Html.Label("Numar", "Numar abonament")
    @Html.TextBox("Numar", null, new { @class = "form-control" })
    @Html.ValidationMessage("Numar", null, new { @class = "text-danger" })
    <br />

    @Html.Label("DataEmitere", "Data emitere abonament")
    @Html.TextBox("DataEmitere", "", new { @class = "form-control datepicker", @placeholder = "Introduceti data" })
    @Html.ValidationMessage("DataEmitere", null, new { @class = "text-danger" })
    <br />

    @Html.Label("ClientId", "Selectati clientul")
    @Html.DropDownList("ClientId", new SelectList(Model.Cls, "Value", "Text"), "Selectati clientul", new { @class = "form-control" })
    @Html.ValidationMessage("ClientId", null, new { @class = "text-danger" })
    <br />

    <button class="btn btn-success" type="submit">Adauga abonament</button>
}

Examen/Subiect1/Views/Subscriptions/Search.cshtml
@{
    ViewBag.Title = "Subscriptions";
}

<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("Search", "Subscriptions", FormMethod.Get))
{
    <input class="form-control text-box single-line search-bar" name="token" type="text" value="@ViewBag.Search" placeholder="data(dd.mm.yyyy) sau descrierea">
}
<br />

@using (Html.BeginForm("Search", "Subscriptions", FormMethod.Get))
{
    var selectList = new List<SelectListItem>();
    selectList.Add(new SelectListItem { Value = "dateDesc", Text = "Noutate (cele mai noi)" });
    selectList.Add(new SelectListItem { Value = "dateAsc", Text = "Noutate (cele mai vechi)" });

    <input name="token" type="hidden" value="@ViewBag.Search">

    <div class="form-group">
        <div class="col-sm-3">
            @Html.DropDownList("sort", new SelectList(selectList, "Value", "Text"), null, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-default">Sorteaza</button>
    </div>
}

@foreach (BiganAntonioM41.Models.Subscription subscription in ViewBag.Subscriptions)
{
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">@subscription.Client.Nume</h3>
    </div>

    <div class="panel-body">
        Descriere: @subscription.Descriere
        <span class="label label-info pull-right">@subscription.DataEmitere.ToString("dd/MM/yyyy")</span>

    </div>

    <div class="panel-footer">
        <a class="btn btn-success btn-sm" href="/Subscriptions/Show/@subscription.Id">Afisare abonament</a>
    </div>
</div>
}

Examen/Subiect1/Views/Subscriptions/Show.cshtml
@model BiganAntonioM41.Models.Subscription

<br />
<a class="btn btn-primary" href="/Subscriptions/Index">Inapoi la abonamente</a>
<br />
<br />

<div class="panel panel-default">
    @Html.Partial("SubscriptionInfo", Model)

    <div class="panel-footer">
        <a class="btn btn-warning" href="/Subscriptions/Edit/@Model.Id">Modifica abonament</a>
        @using (Html.BeginForm("Delete", "Subscriptions", new { id = Model.Id }, FormMethod.Post, new { @class = "pull-right" }))
        {
            @Html.HttpMethodOverride(HttpVerbs.Delete)
            <button class="btn btn-danger" type="submit">Sterge abonament</button>
        }
    </div>
</div>